# Generated by Django 4.0.2 on 2022-02-06 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teammate', '0002_teammate_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammate',
            name='title',
            field=models.CharField(default='Mr.', max_length=10),
        ),
    ]
